name: Project Sicario CI Build

on:
  push:
    branches: [ main ]
    paths-ignore:
      - "docs/**"
      - ".github/workflows/docs.yml"
    tags:
      - 'v*.*.*'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - "docs/**"
      - ".github/workflows/docs.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          submodules: true #only the docs needs recursive
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
      - name: Restore Tools
        shell: bash
        run: |
          dotnet tool restore
      - name: Run the Cake script
        uses: cake-build/cake-action@v1
        with:
          target: Release
        env:
          QUAY_TOKEN: ${{secrets.QUAY_TOKEN}}
          QUAY_USER: project-sicario+github
          NUGET_TOKEN: ${{secrets.NUGET_TOKEN}}
      - uses: actions/upload-artifact@v1
        name: Upload Server
        with:
          name: project-sicario-server
          path: dist/publish/dotnet-any/ # limiting this for now because its huge
      - uses: actions/upload-artifact@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: build_archives
          path: dist/archive/
  build-win:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@master
        with:
          submodules: true
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
      - name: Restore Tools
        run: |
          dotnet tool restore
      - name: Run the Cake script
        uses: cake-build/cake-action@v1
        with:
          target: Publish-Merger
      - uses: actions/upload-artifact@v1
        name: Upload Merger
        with:
          name: project-sicario-merger
          path: dist/merger/win-x64/
      - uses: actions/upload-artifact@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: merger_archives
          path: dist/archive/
  release-gh:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    needs: [build, build-win]
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v1
        with:
          name: build_archives
          path: assets/
      - name: Download build artifact
        uses: actions/download-artifact@v1
        with:
          name: merger_archives
          path: assets/
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./assets/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  nexus:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    needs: build-win
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
    - name: Restore Tools
      shell: bash
      run: |
        dotnet tool install NexusUploader
    - name: Download build artifact
      uses: actions/download-artifact@v1
      with:
        name: merger_archives
        path: assets/
    - name: Set version output
      id: vars
      run: echo ::set-output name=tag::${GITHUB_REF#refs/tags/v}
    - name: Validate unex config
      continue-on-error: true
      shell: bash
      run: |
        dotnet unex check -c
      env:
        UNEX_APIKEY: ${{ secrets.NEXUS_TOKEN }}
        UNEX_COOKIES: ${{ secrets.NEXUS_COOKIES }}
        UNEX_DEBUG: true
    - name: Run Nexus uploader
      shell: bash
      run: |
        dotnet unex upload 270 ./assets/sicario-merger-win-x64.zip -v ${{ steps.vars.outputs.tag }}
      env:
        UNEX_APIKEY: ${{ secrets.NEXUS_TOKEN }}
        UNEX_COOKIES: ${{ secrets.NEXUS_COOKIES }}
        UNEX_DEBUG: true